name: ci

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.18', '1.19']
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: lint
      run: |
        go version
        make lint

    - name: tests
      run: |
        go version
        make test
