name: ci

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.16', '1.17', '1.18']
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        go get github.com/golang/mock/gomock
        go get github.com/golang/mock/mockgen@latest

    - name: lint
      run: make lint

    - name: tests
      run: make test
